# this docker proxy dns make development less painful
# run this if you dont have any docker proxy dns yet

version: "3.5"

services:
  docker-proxy-dns:
    image: defreitas/dns-proxy-server
    ports:
      - "5380:5380"
    hostname: docker-proxy-dns
    container_name: docker-proxy-dns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf