"""empty message

Revision ID: 1624984421869
Revises: 1624983569798
Create Date: 2021-06-29 23:33:42.759785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1624984421869'
down_revision = '1624983569798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['test'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'test')
    # ### end Alembic commands ###
