"""empty message

Revision ID: 1624670005656
Revises: 1622340383395
Create Date: 2021-06-26 08:13:26.345601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1624670005656'
down_revision = '1622340383395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_location',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meeting',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('assignee', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('location_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['meeting_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('slack_team_id', sa.String(), nullable=False))
    op.add_column('project', sa.Column('slack_team_admin_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'project', ['slack_team_admin_id'])
    op.create_unique_constraint(None, 'project', ['name'])
    op.create_unique_constraint(None, 'project', ['slack_team_id'])
    op.add_column('user', sa.Column('slack_id', sa.String(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['slack_id'])
    op.drop_column('user', 'facebook_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'slack_id')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'slack_team_admin_id')
    op.drop_column('project', 'slack_team_id')
    op.drop_table('meeting')
    op.drop_table('meeting_location')
    # ### end Alembic commands ###
