"""empty message

Revision ID: 1624742875772
Revises: 1624670005656
Create Date: 2021-06-27 04:27:56.448601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1624742875772'
down_revision = '1624670005656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meeting_location_name_key', 'meeting_location', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('meeting_location_name_key', 'meeting_location', ['name'])
    # ### end Alembic commands ###
