"""empty message

Revision ID: 1624795398990
Revises: 1624788958650
Create Date: 2021-06-27 19:03:19.669264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1624795398990'
down_revision = '1624788958650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignee', postgresql.UUID(as_uuid=True), nullable=True))
    op.alter_column('task', 'estimated_hours',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'task', 'user', ['assignee'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'estimated_hours',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('task', 'assignee')
    # ### end Alembic commands ###
