"""empty message

Revision ID: 1625015895994
Revises: cceb51725f4b
Create Date: 2021-06-30 08:18:16.784302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1625015895994'
down_revision = 'cceb51725f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slack_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'project', ['slack_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'slack_token')
    # ### end Alembic commands ###
