"""empty message

Revision ID: 1625021242773
Revises: 1625015895994
Create Date: 2021-06-30 09:47:23.593610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1625021242773'
down_revision = '1625015895994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slack_member_monitor_token', sa.String(), nullable=False))
    op.add_column('project', sa.Column('slack_bot_token', sa.String(), nullable=False))
    op.drop_constraint('project_slack_token_key', 'project', type_='unique')
    op.create_unique_constraint(None, 'project', ['slack_member_monitor_token'])
    op.create_unique_constraint(None, 'project', ['slack_bot_token'])
    op.drop_column('project', 'slack_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slack_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.create_unique_constraint('project_slack_token_key', 'project', ['slack_token'])
    op.drop_column('project', 'slack_bot_token')
    op.drop_column('project', 'slack_member_monitor_token')
    # ### end Alembic commands ###
