"""empty message

Revision ID: cceb51725f4b
Revises: 1624984421869
Create Date: 2021-06-30 00:04:21.600633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cceb51725f4b'
down_revision = '1624984421869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_test_key', 'user', type_='unique')
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_test_key', 'user', ['test'])
    # ### end Alembic commands ###
